// Package render generates each IDE's native project rule files from the
// resolved DevBase packs. .devbase/rules stays the source of truth; these
// files are what the IDEs actually read.
package render

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const marker = "<!-- devbase:managed — regenerated by `devbase init`, do not edit by hand -->"

// Section is one pack rule file with its stack scope.
type Section struct {
	Stack string
	Body  string
}

// Files returns target path → content for ideName, or an error for unknown IDEs.
func Files(ideName string, secs []Section) (map[string]string, error) {
	switch ideName {
	case "claude-code":
		return map[string]string{"CLAUDE.md": doc(secs, all)}, nil
	case "opencode", "codex":
		return map[string]string{"AGENTS.md": doc(secs, all)}, nil
	case "cursor":
		out := map[string]string{
			filepath.Join(".cursor", "rules", "devbase-core.mdc"): mdc(
				"DevBase core and security rules for this project", true, secs, coreSec),
		}
		for _, stack := range stacksExcept(secs, "core", "security") {
			out[filepath.Join(".cursor", "rules", "devbase-"+slug(stack)+".mdc")] = mdc(
				"DevBase "+stack+" conventions; use when working with "+stack+" code",
				false, secs, only(stack))
		}
		return out, nil
	case "vscode-copilot":
		return map[string]string{
			filepath.Join(".github", "copilot-instructions.md"): doc(secs, all),
		}, nil
	case "windsurf":
		return map[string]string{
			filepath.Join(".windsurf", "rules", "devbase.md"): windsurfDoc(secs),
		}, nil
	}
	return nil, fmt.Errorf("unknown IDE: %s", ideName)
}

// WriteFiles writes files under dir, backing up existing non-managed files to
// <path>.pre-devbase.bak. Returns the written paths.
func WriteFiles(dir string, files map[string]string) ([]string, error) {
	var written []string
	for rel, content := range files {
		dst := filepath.Join(dir, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
			return written, err
		}
		if data, err := os.ReadFile(dst); err == nil && !strings.Contains(string(data), marker) {
			if err := os.WriteFile(dst+".pre-devbase.bak", data, 0o644); err != nil {
				return written, err
			}
		}
		if err := os.WriteFile(dst, []byte(content), 0o644); err != nil {
			return written, err
		}
		written = append(written, dst)
	}
	return written, nil
}

func all(Section) bool { return true }

func coreSec(s Section) bool { return s.Stack == "core" || s.Stack == "security" }

func only(stack string) func(Section) bool {
	return func(s Section) bool { return s.Stack == stack }
}

func stacksExcept(secs []Section, skip ...string) []string {
	skipSet := map[string]bool{}
	for _, s := range skip {
		skipSet[s] = true
	}
	var out []string
	seen := map[string]bool{}
	for _, s := range secs {
		if skipSet[s.Stack] || seen[s.Stack] {
			continue
		}
		seen[s.Stack] = true
		out = append(out, s.Stack)
	}
	return out
}

func slug(s string) string { return strings.ReplaceAll(s, "/", "-") }

func body(secs []Section, keep func(Section) bool) string {
	var b strings.Builder
	for _, s := range secs {
		if !keep(s) {
			continue
		}
		b.WriteString("<!-- stack: " + s.Stack + " -->\n")
		b.WriteString(strings.TrimSpace(s.Body))
		b.WriteString("\n\n")
	}
	return strings.TrimSpace(b.String()) + "\n"
}

func doc(secs []Section, keep func(Section) bool) string {
	return marker + "\n\n# Project rules (DevBase)\n\n" + body(secs, keep)
}

func mdc(desc string, always bool, secs []Section, keep func(Section) bool) string {
	return "---\ndescription: \"" + desc + "\"\nalwaysApply: " + fmt.Sprintf("%t", always) +
		"\n---\n\n" + marker + "\n\n" + body(secs, keep)
}

func windsurfDoc(secs []Section) string {
	return "---\ntrigger: always_on\ndescription: \"DevBase project rules\"\n---\n\n" +
		marker + "\n\n" + body(secs, all)
}
